#request
bool verbose
uint16 waypointIndex
uint16 actionId
string missionId
---
#response
bool success
bool withStation
dji_osdk_ros/WaypointV2InitSetting waypoints
dji_osdk_ros/WaypointV2Action[] actions
string state
string missionId